### ISSUE TITLE
How to authenticate ?

### ISSUE THREAD

**Issue by AaronO** [onesysadmin/ubuntu-postfix#1]
`postfix` doesn't seem to be running with `smtpd_sasl_auth_enable=no`. So how do you authenticate to `postfix`, what are it's credentials ?

**Comment by asans** [comment]
`smtpd_sasl_auth_enable` is not set or touched by the docker container.  It should be installed without sasl installed.

http://www.postfix.org/postconf.5.html

So there should be no SASL enabled in this instance.  If you telnet and perform some tests to see what options it gives you:

```
% telnet server.example.com 25
...
220 server.example.com ESMTP Postfix
EHLO client.example.com
250-server.example.com
250-PIPELINING
250-SIZE 10240000
250-AUTH DIGEST-MD5 PLAIN CRAM-MD5
```

You should see `AUTH DIGEST-MD5 ...` if smtpd_sasl_auth_enable is enabled.  If you don't see that as an option, then it's not enabled.
